config/routes.rb
Rails.application.routes.draw do


devise_for :user do
   get "/login", :to => "devise/sessions#new" # Add a custom sign in route for user sign in
   get "/logout", :to => "devise/sessions#destroy" # Add a custom sing out route for user sign out
   get "/register", :to => "devise/registrations#new" # Add a Custom Route for Registrations
end

  # devise_scope :user do
  #   get '/users' to: 'devise/registrations#new'
  #   get '/users/password' to: 'devise/passwords#new'
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
   # devise_for :users
  # devise_for :users,  controllers: {
  #       sessions: 'users/sessions',
  #       passwords: 'users/passwords',
  #       registrations: 'users/registrations',
  #       confirmations: 'users/confirmations'    
  # }
  get 'home/about'
  get 'posts/myposts'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: { minimum: 5, maximum: 100}
	validates :description, presence: true, length: { minimum: 5, maximum: 700}
	validates :keyword, presence: true, length: { minimum: 5, maximum: 100}
	has_many_attached :images

	belongs_to :user
	before_create :randomize_id
	private
  	def randomize_id
    	begin 
      	self.id = SecureRandom.random_number
        (1_000_000_000)
	  	end 
	  # while
	  # User.where(id: self.id)exists?
  end         
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :posts
        
        before_create :randomize_id
        private
          def randomize_id
            begin 
              self.id = SecureRandom.random_number
                (1_000_000_000)
            end 
            # while
             # User.where(id: self.id)exists?
          end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def myposts
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

     respond_to do |format|
      if @post.save
         format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
         format.json { render :show, status: :created, location: @post }
      else
        # render :new
         format.html { render :new, status: :unprocessable_entity }
         format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keyword, :user_id, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'post' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header"%>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="col-xl-4 col-md-6 col-sm-8 col-10" style="margin: auto; background-color: #f8f8f8; border-radius: 6px; padding: 15px; box-shadow: 0px 0px 2px 2px(255, 255, 255, 0.1);">
  <%= form_with(model: post) do |form| %>
    <h1 class="text-primary">New post</h1>
     <div>
      <% invalid = post.errors.include?(:title)%>
       <%= form.label :title, style: "display: block" %>
       <%= form.text_field :title, class: "form-control" %>
      <% if invalid %>
        <p class="text-danger">
        <%= post.errors.full_messages_for(:title).join(" , ")%>
        </p>
      <% end %>
    </div>
    <div>
      <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
    </div>
    <div>
      <% invalid = post.errors.include?(:description)%>
       <%= form.label :description, style: "display: block" %>
       <%= form.text_field :description, class: "form-control" %>
      <% if invalid %>
        <p class="text-danger">
        <%= post.errors.full_messages_for(:description).join(" , ")%>
        </p>
      <% end %>
    </div>
    <div>
      <% invalid = post.errors.include?(:keyword)%>
       <%= form.label :keyword, style: "display: block" %>
        <%= form.text_field :keyword, class: "form-control" %>
      <% if invalid %>
       <p class="text-danger">
        <%= post.errors.full_messages_for(:keyword).join(" , ")%>
       </p>
      <% end %>
      <%= form.file_field :images, multiple:true%>
    </div>
    <div>
      <%= form.submit class: "btn btn-primary col-12"%>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class= "post-container">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>
  <p>
    <strong>Keyword:</strong>
    <%= post.keyword %>
  </p>
  <p>
    <strong>Email:</strong>
    <%#= post.user.email  %>
  </p>
  <p>
    <%= link_to "Show this post", post, class: "post-link" %>
  </p>
  <% post.images.each do |image| %>
    <%= image_tag(image, style: "object_fit: contain; width: 200px; height: 200px") %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<!-- <div class="col-xl-4 col-md-6 col-sm-8 col-10" style="margin: auto; background-color: #f8f8f8; border-radius: 6px; padding: 15px; box-shadow: 0px 0px 2px 2px(255, 255, 255, 0.1);"> -->
  <!-- <h1>Editing post</h1> -->
  <%= render "form", post: @post %>
  <br>
  <div class="text-center">
    <%= link_to "Show this post", @post, class: "nav-link" %> 
    <%= link_to "Back to posts", posts_path, class: "nav-link" %>
  </div>

app/views/posts/index.html.erb
<p class="text-success"><%= notice %></p>
<h1 class="devv">Posts</h1>
<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>

app/views/posts/myposts.html.erb
<p class="text-success"><%= notice %></p>
<h1 class="devv">Posts</h1>
<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <% if post.user.id == current_user.id %>
      <%= render post %>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <%= render "form", post: @post %>
</div>

<br>


<div class="col-xl-4 col-md-6 col-sm-8 col-10" style="margin: auto; background-color: #f8f8f8; border-radius: 6px; padding: 15px; box-shadow: 0px 0px 2px 2px(255, 255, 255, 0.1);">
  <%= link_to "Back to posts", posts_path, class: "nav-link " %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post), class: "nav-link" %> 
  <%= link_to "Back to posts", posts_path, class: "nav-link" %>

  <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-primary" %>
</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-secondary text-light  ">
  <!-- Section: Social media -->
  <!-- <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"> -->
    <!-- Left -->
    <!-- <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div> -->
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  <!-- </section> -->
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
             <%= link_to 'Home', root_path, class:  'nav-link active   navbar-brand' %>
          </p>
          <p>
             <%= link_to 'About', home_about_path, class:  'nav-link active  navbar-brand' %>
          </p>
          <p>
           <% if user_signed_in? %>
              <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link active" %> <br>
             <%= link_to 'Edit-Account', edit_user_registration_path, class: "nav-link active" %>
           <% else %>
              <%= link_to 'Sign In', new_user_session_path, class: "nav-link active" %>
           <% end %>
          </p>
          <p>
            <!-- <a href="#!" class="text-reset">User</a> -->
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6> <p><i
          class="fas fa-home me-3"></i> Pu4, Indore, (M.P.) , India </p> <p>
          <i class="fas fa-envelope me-3"></i> instaclone@example.com </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p> <p><i
          class="fas fa-print me-3"></i> + 01 234 567 89</p> </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="http://localhost:3000/">Local-Host</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Instaclone', root_path, class:  'nav-link active text-danger navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to "Upload post", new_post_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", home_about_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
         <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Edit-Account', edit_user_registration_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to 'View Post', posts_myposts_path, class: "nav-link active" %>
            </li>
         <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "nav-link active" %>
            </li>
         <% end %>
       </li>
       
         
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>